### PR TITLE
Migrated PlayerIOClient to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by Daddoon**
- Migrated PlayerIOClient to .NET Standard 2.0
- Tested basic functionnality on Windows (Windows 10) - SimpleRegister, with OpenPlayerIO/PlayerIOServer
- Tested basic functionnality on Linux (Debian 10) - SimpleRegister, with OpenPlayerIO/PlayerIOServer

### CODE REVIEW

**Comment by atillabyte** [comment]
LGTM. Thanks!

**Comment by Daddoon** [comment]
Haha i didn't seen that you have the Venture repo, so this is a bit late.

I have seen this current implementation still contain some System.Dynamic (ExpdandoObject and dynamic keyword), so it should have issues on AOT environments like iOS / Unity WebGL / Blazor.

But i have seen that you already have removed theses kind of reference on the Venture repo, so it's like already done somehow haha.

**Comment by Daddoon** [comment]
Also be aware that this commit does NOT do any ILMerge.

**Comment by miou-gh** [comment]
No problem. :)

I have not tested with Unity or Blaxor but it'd be cool Venture worked on those platforms.

**Comment by Daddoon** [comment]
I will surely do some try with the Venture one on Unity in some days. I will try to keep you informed.

I think it will work to any HTTP workload on theses platform, however the multiplayer API should:

- Work on Unity3D Native client
- Work on Blazor server-side client (altough it would be a very weird combination !)
- Don't work on Unity3D WebGL as the browser can only connect to a Websocket, not a socket
- Don't work on Blazor WebAssembly as the browser can only connect to a Websocket, not a socket

At least i would have to do some custom modification and doing some bridge with websockify (for exemple), in order to allow a WebSocket connection to be redirected to Socket.

But this would also implie that there is also a WebSocket client library support included in your Venture/PlayerIOClient API too that can bridge to JS WebSocket.

Anyway, if i find some improvement on my side on this too, i will tell you informed !

**Pull request merged**
